/**
 * hey-api's @tanstack/react-query plugin classifies operations as query vs.
 * mutation purely by HTTP method (GET -> query, POST -> mutation). Our list
 * endpoint is POST /auctions/list (filters live in the body, too large for
 * query params) but is semantically a search/list query, not a mutation —
 * so hey-api generated `listAuctionsMutation` instead of query options, and
 * consequently no infinite-query variant either (only detected on queries).
 *
 * This file hand-authors the query-shaped options hey-api would have
 * produced if it treated POST /auctions/list as a query, using the same
 * queryKey shape as the generated getAuctionOptions/listBetsOptions. Not
 * regenerated by `npx openapi-ts` — kept in sync manually (see
 * .claude/skills/generate-api).
 */
import { infiniteQueryOptions, queryOptions } from '@tanstack/react-query'

import { listAuctions, type Options } from './generated/sdk.gen'
import type { AuctionListRequest, ListAuctionsData, ListAuctionsError, ListAuctionsResponse } from './generated/types.gen'

type ListAuctionsQueryKeyEntry = {
  _id: 'listAuctions'
  _infinite?: true
  body?: AuctionListRequest
}

// Single-client, single-baseUrl app: unlike hey-api's own createQueryKey, we
// don't key on baseUrl (its generic type resolves oddly through the
// generated Options<TData> chain, and we never override it per-call anyway).
const buildKeyEntry = (options: Options<ListAuctionsData>, infinite?: true): ListAuctionsQueryKeyEntry => ({
  _id: 'listAuctions',
  ...(infinite ? { _infinite: infinite } : {}),
  ...(options.body ? { body: options.body } : {}),
})

export const listAuctionsQueryKey = (options: Options<ListAuctionsData>) => [buildKeyEntry(options)] as const

export const listAuctionsOptions = (options: Options<ListAuctionsData>) =>
  queryOptions<ListAuctionsResponse, ListAuctionsError, ListAuctionsResponse, ReturnType<typeof listAuctionsQueryKey>>({
    queryFn: async ({ signal }) => {
      const { data } = await listAuctions({ ...options, signal, throwOnError: true })
      return data
    },
    queryKey: listAuctionsQueryKey(options),
  })

export const listAuctionsInfiniteQueryKey = (options: Options<ListAuctionsData>) => [buildKeyEntry(options, true)] as const

export const listAuctionsInfiniteOptions = (options: Options<ListAuctionsData>) =>
  infiniteQueryOptions<ListAuctionsResponse, ListAuctionsError, ListAuctionsResponse, ReturnType<typeof listAuctionsInfiniteQueryKey>, number>({
    initialPageParam: 1,
    getNextPageParam: (lastPage) => {
      const meta = lastPage.meta
      if (!meta || meta.current_page === undefined || meta.last_page === undefined) return undefined
      return meta.current_page < meta.last_page ? meta.current_page + 1 : undefined
    },
    queryFn: async ({ pageParam, signal }) => {
      const { data } = await listAuctions({
        ...options,
        body: { ...options.body, page: pageParam },
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listAuctionsInfiniteQueryKey(options),
  })
